# Generated by Django 5.1.5 on 2025-01-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=500, unique=True, verbose_name='Токен'),
        ),
    ]
