# Generated by Django 5.1.5 on 2025-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('uid', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID пользователя')),
            ],
            options={
                'db_table': 'whitelist',
            },
        ),
    ]
